export const idLang = {
    rfid: 'Perangkat RFID',
    lang: 'Ubah ke Bahasa Inggris',
    theme: {
        light: 'Ubah ke Tema Light',
        dark: 'Ubah ke Tema Dark'
    },
    home: 'Beranda',
    assistant: 'Asisten',
    calas_s: 'CALAS',
    calas_l: 'Calon Asisten',
    assistantAtd: 'Presensi Asisten',
    calasAtd: 'Presensi CALAS',
    calasAtd_l: 'Presensi Calon Asisten',
    absent: 'Izin',
    addAbsent: 'Tambah Izin',
    totalActiveassistant: 'Jumlah Asisten Aktif',
    totalActiveCalas: 'Jumlah Calon Asisten Aktif',
    totalAtdnow: 'Jumlah Presensi Hari Ini',
    totalAbsentNow: 'Jumlah Izin Hari Ini',
    exportcard: 'Export Presnsi',
    facultDep: 'Fakultas & Jurusan',
    gender: 'Jenis Kelamin',
    entryYear: 'Tahun Masuk',
    male: 'Laki - Laki',
    female: 'Perempuan',
    position: 'Jabatan',
    addMoreAssistant: 'Tambah Asisten Baru',
    dataAsistant: 'Data Asisten',
    search: 'Cari',
    name: 'Nama',
    fullName: 'Nama Lengkap',
    email: 'Alamat Surel',
    phoneNumber: 'Nomor Handphone',
    cardSerialNumber: 'Nomor Serial Kartu',
    password: 'Kata Sandi',
    cancel: 'Batal',
    save: 'Simpan',
    edit: 'Ubah',
    delete: 'Hapus',
    disableIt: 'Nonaktifkan',
    enableit: 'Aktifkan',
    addAtd: 'Tambah Presensi',
    comeAtd: 'Tambah Presensi Datang',
    homeWrdAtdadd: 'Tambah Presensi Pulang',
    homewardAtd: 'Presensi Pulang',
    dateNow: 'Waktu Saat Ini',
    changeDate: 'Ganti Tanggal',
    changeDateAtd: 'Ganti Tanggal Presensi',
    chooseAssistant: 'Pilih Asisten',
    scsAddAtd: 'Berhasil Menambahkan Presensi',
    changeAssistantData: 'Ubah Asisten Data',
    saveChange: 'Simpan Perubahan',
    startTime: 'Waktu Awal',
    endTime: 'Waktu Akhir',
    selReport: 'Pilih Laporan Yang akan Dicetak',
    all: 'Semua',
    print: 'Cetak',
    to: 'S/d',
    notpresent: 'Tidak Hadir',
    present: 'Hadir',
    getHome: 'Pulangkan',
    onTime: 'Tepat Waktu',
    late: 'Terlambat',
    dlyAtdRecap: 'Rekap Absen Harian',
    dlyAbsentRecap: 'Rekap Izin Harian',
    changeAbsentDate: 'Ganti Waktu Izin',
    info: 'Keterangan',
    regisDate: 'Tanggal Register',
    previewAtdRerport: 'Pertinjau Laporan Presensi',
    period: 'Periode',
    totalDay: 'Jumlah Hari',
    somethingError: "Terjadi Suatu Kesalahan!",
    welcome: "Selamat Datang",
    yes: "Ya",
    no: "Tidak",
    sureLogOut: "Anda yakin ingin keluar?",
    dept: "Jurusan",
    scssEnableDisable: "Sukses Mengaktifkan/Menonaktifkan",
    failEnableDisable: "Gagal Mengaktifkan/Menonaktikannya",
    scssDelete: "Sukses Menghapus data ",
    failDelete: "Gagal menghapus data",
    scssEdit: "Sukses Merubah data",
    failEdit: "Gagal merubah data",
    scssAdd: "Sukses menambahkan data baru",
    failAdd: "Gagal menambahkan data baru",
    failGet: "Gagal memperoleh data",
    addNewDevice: "Tambah Perangkat Baru",
    editDevice: "Ubah Perangkat",
    scssUpdate: 'Sukses Memperbarui Data',
    failUpdate: "Gagal Memperbarui Data",
    noData: "Tidak ada data",
    cameTime: "Waktu Datang",
    returnTime: "Waktu  Pulang",
    minutes: "Menit",
    on: "di",
    timeRegion: "id-ID",
    failGetServerTime: "Gagal mendapat waktu server",
    failAttd: "Gagal melakukan absensi",
    failOut: "Gagal Melakukan absensi pulang",
    addOut: "Tambah Izin",
    editLeave: "Ubah Izin",
    pageNotFound: "Halaman tidak ditemukan"
}

export const enLang = {
    rfid: 'RFID Devices',
    lang: 'Switch to Bahasa',
    theme: {
        light: 'Switch to Light Theme',
        dark: 'Switch to Dark Theme'
    },
    home: 'Home',
    assistant: 'Assistant',
    calas_s: 'CALAS',
    calas_l: 'Candidate Assistant',
    assistantAtd: 'Assistant Attendance',
    calasAtd: 'CALAS Attendance',
    calasAtd_l: 'Candidate Assistant Attendance',
    absent: 'Leave',
    addAbsent: 'Add Leave',
    totalActiveassistant: 'Total Active Assistants',
    totalActiveCalas: 'Total Active Candidates',
    totalAtdnow: 'Total Present Today',
    totalAbsentNow: 'Total Leave Today',
    exportcard: 'Export Attendance',
    facultDep: 'Faculties & Departments',
    gender: 'Gender',
    entryYear: 'Entry Year',
    male: 'Male',
    female: 'Female',
    position: 'Position',
    addMoreAssistant: 'Add New Assistant',
    dataAsistant: 'Assistant Data',
    search: 'Search',
    name: 'Name',
    fullName: 'Full Name',
    email: 'Email Address',
    phoneNumber: 'Phone Number',
    cardSerialNumber: 'Card Serial Number',
    password: 'Password',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    disableIt: 'Disable',
    enableit: 'Enable',
    addAtd: 'Add Attendance',
    comeAtd: 'Add Arrival Attendance',
    homeWrdAtdadd: 'Add Home Attendance',
    homewardAtd: 'Home Attendance',
    dateNow: 'Current Time',
    changeDate: 'Change Date',
    changeDateAtd: 'Change Attendance Date',
    chooseAssistant: 'Choose Assistant',
    scsAddAtd: 'Successfully Added Attendance',
    changeAssistantData: 'Change Assistant Data',
    saveChange: 'Save Change',
    startTime: 'Start Time',
    endTime: 'End Time',
    selReport: 'Select the report to print',
    all: 'All',
    print: 'Print',
    to: 'to',
    notpresent: 'Not Present',
    present: 'Present',
    getHome: 'Send it Home',
    onTime: 'On Time',
    late: 'Late',
    dlyAtdRecap: 'Daily Attendance Recap',
    dlyAbsentRecap: 'Daily Leave Recap',
    changeAbsentDate: 'Change Leave Date',
    info: 'Reason',
    regisDate: 'Register Date',
    previewAtdRerport: 'Preview Attendance Report',
    period: 'Period',
    totalDay: 'Total Days',
    somethingError: "Something went wrong!",
    welcome: "Welcome",
    yes: "Yes",
    no: "No",
    sureLogOut: "Are you sure want to logout?",
    dept: "Department",
    scssEnableDisable: "Successfully Enabled/Disabled",
    failEnableDisable: "Failed to enable/disable.",
    scssDelete: "Successfully Deleted",
    failDelete: "Fail to delete.",
    scssEdit: "Successfully Edited",
    failEdit: "Fail to edit.",
    scssAdd: "Successfully Added",
    failAdd: "Fail to add.",
    failGet: "Fail to Get data.",
    addNewDevice: "Add New Device",
    editDevice: "Edit Device",
    scssUpdate: "Successfully Updated",
    failUpdate: "Fail to Update",
    noData: "No Data",
    cameTime: "Came Time",
    returnTime: "Return Time",
    minutes: "Minutes",
    on: "on",
    timeRegion: "en-US",
    failGetServerTime: "Failed to get server time",
    failAttd: "Failed to perform attendance",
    failOut: "Failed to perform home attendance",
    addOut: "Add Out",
    editLeave: "Edit Leave",
    pageNotFound: "Page Not Found"
};