name: Deploy FrontEnd

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Pull Code from Main Branch
        run: |
          git pull origin main

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Install Dependencies
        run: |
          npm install

      # - name: Build the App
      #   run: |
      #     npm run build
          
      # - name: Restart the pm2
      #   run: pm2 restart 5
